version: '3.8'

services:
  materialized:
    image: materialize/materialized:latest
    ports:
      - "6875:6875"
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--set wal_level=logical"
    restart: always

